'use client';
import ResearchNav from '../components/Marketing/ResearchNav';
import { PageHeader } from '../components/Marketing/PageHeader';
import ResearchFooter from '../components/Marketing/ResearchFooter';

export default function TermsPage() {
    return (
        <main className="min-h-screen bg-white text-slate-900 font-sans selection:bg-indigo-100">
            <ResearchNav />
            <PageHeader
                label="Legal"
                title="Terms of Service"
                subtitle="Governing the use of Prema A.V.E.A and associated research services."
            />

            <section className="px-6 pb-32 max-w-3xl mx-auto">
                <article className="prose prose-slate prose-lg max-w-none">
                    <h3>1. Acceptance of Terms</h3>
                    <p>
                        By accessing or using Prema A.V.E.A ("the Agent"), you agree to be bound by these Terms. The Agent is a research preview and production tool provided by Prema Research.
                    </p>

                    <h3>2. Nature of Autonomy</h3>
                    <p>
                        You acknowledge that A.V.E.A is an <strong>autonomous system</strong>. It makes editorial decisions based on probabilistic models. While we strive for alignment with your intent, the Agent may generate unexpected results ("Hallucinations" or "Creative Drift"). You accept responsibility for reviewing all output before public distribution.
                    </p>

                    <h3>3. Intellectual Property regarding Output</h3>
                    <p>
                        <strong>You retain ownership</strong> of your input footage and the final video output. Prema Research claims no ownership over the content generated by the Agent using your assets.
                    </p>
                    <p>
                        However, you grant Prema Research a limited, non-exclusive license to process your assets solely for the purpose of fulfilling your service requests.
                    </p>

                    <h3>4. Liability Limitation</h3>
                    <p>
                        The Service is provided "AS IS". Prema Research makes no warranties regarding the uptime or accuracy of the Agent's decisions. We constitute no liability for deadlines missed or creative disagreements with the Agent's output.
                    </p>

                    <h3>5. Prohibited Use</h3>
                    <p>
                        You may not use the Agent to generate:
                    </p>
                    <ul className="list-disc pl-6">
                        <li>Deepfakes intended to deceive or harm.</li>
                        <li>Non-consensual sexual content.</li>
                        <li>Political misinformation or hate speech.</li>
                    </ul>
                    <p>
                        Violation of these terms will result in immediate termination of API access and potential legal action.
                    </p>

                    <hr className="my-12 border-slate-200" />

                    <p className="text-sm text-slate-500">
                        Last Updated: December 28, 2025<br />
                        Contact: legal@prema.ai
                    </p>
                </article>
            </section>

            <ResearchFooter />
        </main>
    );
}
